config/routes.rb
Rails.application.routes.draw do
  # ...

  devise_for :users

  root 'pages#home'

  resources :posts
  resources :subscribers
  resources :profiles, only: [:show, :destroy]
  # Ajoutez les routes pour gérer les abonnements et les newsletters

  # Pour afficher la liste des newsletters disponibles
  resources :newsletters, only: [:index, :show]

  # Pour permettre aux utilisateurs de s'abonner et se désabonner
  resources :subscriptions, only: [:create, :destroy]

  # Pour envoyer une newsletter (vous pouvez protéger cette route par exemple)
  post 'newsletters/:id/send', to: 'newsletters#send_newsletter', as: 'send_newsletter'

  # ...
  post '/attachments', to: 'attachments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_many :subscriptions

  validates :subject, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  # Validations
  validates :title, presence: true
  validates :category, presence: true, inclusion: { in: ['Comprendre l\'actualité', 'Créer le futur', 'Arts et culture', 'Méditation et spiritualité', 'Événements et Inscriptions'] }
  validates :content, presence: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  has_many :subscriptions

  validates :surname, presence: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :category, presence: true, inclusion: { in: ['Comprendre l\'actualité', 'Créer le futur', 'Arts et culture', 'Méditation et spiritualité', 'Événements et Inscriptions'] }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :subscriber
  belongs_to :newsletter
end

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_user_type
  # Associations
  has_many :posts, dependent: :destroy

  # Validations
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :user_type, presence: true, inclusion: { in: %w[admin poster user] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
  user_type == "admin"
  end

  def poster?
    user_type == "poster"
  end

  # include Administration

  validate :check_user_type_change, on: :update

  def check_user_type_change
    errors.add(:user_type, "Vous ne pouvez pas changer le user_type.") if user_type_changed? && !can_change_user_type?
  end

  private

  def set_default_user_type
    self.user_type ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.order(created_at: :desc)
    @latest_post = Post.order(created_at: :desc).first
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      cookies[:saved_lead] = true
      redirect_to root_path, notice: "Votre inscription a été prise en compte."
    else
      # Traiter les erreurs de validation si nécessaire
      redirect_to root_path, alert: "Il y a eu un problème lors de votre inscription."
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:surname, :name, :email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pundit::Authorization

  def index
     @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    skip_authorization
  end

  def new
    @post = Post.new
    @subscriber = Subscriber.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    authorize @post

    if @post.save
      @post.image.attach(params[:post][:image])
      @post.video.attach(params[:post][:video])
      redirect_to root_path, notice: "Le post a été créé avec succès."
    else
      render 'new'
    end
  end


  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(post_params)
      # Utilisez Turbo Streams pour mettre à jour la fenêtre Turbo Frame dans la vue d'édition
      redirect_to root_path, notice: "Le post a été mis à jour avec succès."
    else
      # Redirige vers l'action d'édition en cas d'erreur
      render :edit
    end
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to root_path, notice: "L'article a été supprimé avec succès."
  end

  private

  def post_params
    params.require(:post).permit(:title, :category, :content, :image) # Ajoutez d'autres attributs autorisés si nécessaire
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
include Pundit
  before_action :authenticate_user!

  def show
    @subscriber = Subscriber.new
    @user = current_user
    authorize @user
    @posts = Post.where(user_id: current_user.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to root_path, notice: "L'article a été supprimé avec succès."
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscribers = Subscriber.all
  end

  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      NewsletterMailer.welcome_subscriber(@subscriber).deliver_now
      cookies[:saved_lead] = true
      redirect_to root_path, notice: "Votre inscription a été prise en compte."
    else
      # Traiter les erreurs de validation si nécessaire
      redirect_to root_path, alert: "Vous êtes déjà inscrit à notre Newsletter !"
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :surname, :email, category_ids: [])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cara.news</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>

    <!-- Place the first <script> tag in your HTML's <head> -->
    <script src="https://cdn.tiny.cloud/1/mpieyjs1df9b8d2xzmi1msvy4wd7ybe4a81t09uhj0ky6qoe/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
  </head>

  <body>
     <%= render "shared/navbar" %>
      <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
      <% end %>
    <% if alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
    <% end %>
    <%= yield %>

    <!-- Place the following <script> and <textarea> tags your HTML's <body> -->
    <script>
      tinymce.init({
        selector: 'textarea',
        plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
      });
    </script>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Main container -->

<!-- <% if cookies[:saved_subscriber] %>
  <div class="success-message">
    <p>Vous êtes inscrit !</p>
  </div>
<% else %>
  <div class="newsletter-form">
    <%= form_for @subscriber do |f| %>
      <%= f.text_field :name, placeholder: "Nom", class: "input-field" %>
      <%= f.text_field :surname, placeholder: "Prénom", class: "input-field" %>
      <%= f.email_field :email, placeholder: "E-mail", class: "input-field" %>
      <%= f.select :category, options_for_select(["Actualité", "Culture"]), {}, class: "input-field" %>
      <%= f.submit "S'inscrire à la Newsletter", class: "submit-button" %>
    <% end %>
  </div>
<% end %>
-->
<div class="container py-4">
  <h3>A la une</h3>
  <div class="mt-3 cards-hp mx-auto">
    <% if @latest_post %>
      <div class="card-custom">
        <%= content_tag :span, @latest_post[:category], class: "category-style mb-2" %>
        <% if @latest_post.image.attached? %>
          <% if @latest_post.image.variable? %>
            <%= image_tag @latest_post.image, class: "card-image" %>
          <% else %>
            <video controls class="card-image">
              <source src="<%= url_for(@latest_post.image) %>" type="video/mp4">
              Your browser does not support the video tag.
            </video>
          <% end %>
        <% end %>
        <div class="card-details">
          <strong><%= link_to @latest_post[:title], post_path(@latest_post[:id]), class: "card-title" %></strong>
        </div>
      </div>
      </div>
    <% end %>
  </div>
</div>



<div class="container py-4">
  <h3>Derniers articles en ligne</h3>
      <div class="mt-3 cards-hp mx-auto">
        <% @posts.each do |post| %>
          <div class="card-trip">
            <%= content_tag :span, post[:category], class: "category-style mb-5" %>
            <% if post.image.attached? %>
              <% if post.image.variable? %>
                <%= image_tag post.image %>
            <% else %>
              <video controls>
                <source src="<%= url_for(post.image) %>" type="video/mp4">
                Your browser does not support the video tag.
              </video>
            <% end %>
          <% end %>
            <div class="card-trip-infos mt-1">
              <div>
                <strong><%= link_to post[:title], post_path(post[:id]), style: "color: #8583C0; font-size: 22px;" %></strong>
              </div>
            </div>
          </div>
        <% end %>
      </div>
</div>

app/views/posts/edit.html.erb
    <h2>Modifier l'article</h2>
<div class="container pt-5">
  <%= simple_form_for @post, data: { turbo: false }, html: { class: "form" } do |form| %>
    <div class="form-inputs">
      <%= form.input :title, label: "Modifier le titre", input_html: { class: "form-control" } %>
      <%= form.input :category, label: "Modifier la catégorie", input_html: { class: "form-control" } %>
      <label for="post_content">Modifier le contenu</label>
      <%= form.text_area :content, id: "post_content" %>

      <br>
      <h3>Image attachée à l'article</h3>
        <% if @post.image.attached? %>
          <% if @post.image.variable? %>
            <%= cl_image_tag @post.image.key, class: "post-edit" %>
          <% else %>
            <video controls width="200" height="150" class="post-video">
              <source src="<%= url_for(@post.image) %>" type="video/webm">
              Your browser does not support the video tag.
            </video>
           <% end %>
         <% end %>
        <%= form.file_field :image, label: "URL de l'image", input_html: { class: "form-control" } %>
    </div>
    <br />
    <div class="form-actions">
      <div class="d-flex justify-content-between">
        <%= form.button :submit, "Modifier l'article", class: "btn btn-primary" %>
      </div>
    </div>
    <br />
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container pt-5 mb-5">
  <%= simple_form_for @post, data: { turbo: false }, html: { class: "form", id: "post-form" } do |form| %>
<div class="form-inputs">
  <%= form.input :title, label: "Titre de l'article", input_html: { class: "form-control" } %>
  <%= form.input :category, label: "Catégorie de l'article", as: :select, collection: ['Comprendre l\'actualité', 'Créer le futur', 'Arts et culture', 'Méditation et spiritualité', 'Événements et Inscriptions'], prompt: "Sélectionner une catégorie", input_html: { class: "form-control" } %>
<div class="form-group">
  <label for="post_content">Contenu de l'article</label>
  <textarea id="post_content" name="post[content]" style="width: 100%; min-height: 500px;"></textarea>
</div>
  <br>
  <%= form.file_field :image, label: "URL de l'image", input_html: { class: "ctsm-btn", id: "image-input" } %>
</div>

    <br>
    <div class="cstm-btn-container">
      <%= form.button :submit, "Créer l'article", class: "cstm-btn" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container-post mt-3 mb-3">
  <h2><%= @post.title %></h2>
  <p class="post-category"><%= @post.category %></p>
  <p class="post-date"><%= @post.created_at.strftime("%d %B %Y") %></p>
  <% if @post.image.attached? %>
    <% if @post.image.variable? %>
      <%= cl_image_tag @post.image.key, class: "post-image" %>
    <% else %>
      <div class="video-container">
        <video controls class="post-video">
          <source src="<%= url_for(@post.image) %>" type="video/webm">
          Your browser does not support the video tag.
        </video>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <div class="content">
      <%= @post.content.html_safe %>
    </div>
  </div>
  <% if user_signed_in? && current_user == @post.user %>
    <div class="d-flex justify-content-between">
      <%= link_to "Editer l'article", edit_post_path(@post), class: "btn btn-primary" %>
      <%= button_to "Supprimer", {:controller => :posts, :action => 'destroy', :id => @post.id }, :method => :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center">
    <h3>Vos articles en ligne</h3>
    <%= link_to "Créer un article", new_post_path, class: "cstm-btn" %>
  </div>
  <div class="mt-3 cards-hp mx-auto">
    <% @posts.each do |post| %>
      <% if post.user == current_user %>
        <div class="card-trip">
          <% if post.image.attached? %>
            <% if post.image.variable? %>
              <%= image_tag post.image %>
            <% else %>
              <video controls>
                <source src="<%= url_for(post.image) %>" type="video/mp4">
                Your browser does not support the video tag.
              </video>
            <% end %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <strong><%= link_to post.title, post_path(post) %></strong>
            </div>
              <% if post.user == current_user %>
                <%= link_to "Modifier", edit_post_path(post), class: "btn btn-primary" %>
                <%= button_to "Supprimer", {:controller => :posts, :action => 'destroy', :id => post.id }, :method => :delete, class: "btn btn-danger" %>
              <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <div class="navbar navbar-expand-sm navbar-light navbar">
    <div class="container ml-5">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "Logo_CaraNews_blanc.png", style: "width: 100%; height: auto;" %>
      <% end %>
    </div>
    <div class="container">
      <p>«Tout ce que l'homme ignore n'existe pas pour lui.
          Donc, l'univers de chacun se résume à la taille de ses connaissances. »Albert Einstein
      </p>
    </div>
    <div class="container">
      <div class="nav-item">
        <%= link_to "Qui sommes-nous ?", new_post_path, class: "nav-link custom-home-link" %>
      </div>
      <div class="nav-item">
        <%= link_to "Contact", new_post_path, class: "nav-link custom-home-link" %>
      </div>
      <div class="footer-links">
        <a href="#"><i class="fab fa-youtube"></i></a>
        <a href="#"><i class="fab fa-telegram"></i></a>
      </div>
    </div>
    <div class="container">
      <%= link_to "S'inscrire à la Newsletter", new_subscriber_path, class: "cstm-btn" %>
    </div>
  </div>




  <div class="navbar navbar-expand-sm navbar-light navbar-mini">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mx-auto">
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to "Home", root_path, class: "nav-link custom-home-link" %>
          </li>

          <% if current_user.user_type.in?(['admin', 'poster']) %>
            <!-- Bouton spécifique pour les administrateurs et posteurs -->
            <li class="nav-item <%= 'active' if current_page?(new_post_path) %>">
              <%= link_to "Créer un article", new_post_path, class: "nav-link custom-home-link" %>
            </li>
          <% end %>
          <% if current_user.user_type.in?(['admin']) %>
            <!-- Bouton spécifique pour les administrateurs et posteurs -->
            <li class="nav-item <%= 'active' if current_page?(subscribers_path) %>">
              <%= link_to "Liste", subscribers_path, class: "nav-link custom-home-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mon Compte
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link custom-home-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/subscribers/index.html.erb
<!-- app/views/subscribers/index.html.erb -->
<h2>Liste des Abonnés</h2>

<div class="container mt-5 mb-5">
  <table class="subscribers-table">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
        <th>Catégorie</th>
      </tr>
    </thead>
    <tbody>
      <% @subscribers.each do |subscriber| %>
        <tr>
          <td><%= subscriber.name %></td>
          <td><%= subscriber.surname %></td>
          <td><%= subscriber.email %></td>
          <td><%= subscriber.category %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subscribers/new.html.erb
<% if cookies[:saved_subscriber] %>
  <div class="success-message">
    <p>Vous êtes inscrit !</p>
  </div>
<% else %>
  <div class="container-post mt-10">
      <%= form_for @subscriber, html: { class: "subscriber-form" } do |f| %>
      <%= f.text_field :name, placeholder: "Nom", class: "input-field" %>
      <%= f.text_field :surname, placeholder: "Prénom", class: "input-field" %>
      <%= f.email_field :email, placeholder: "E-mail", class: "input-field" %>
      <% ['Comprendre l\'actualité', 'Créer le futur', 'Arts et culture', 'Méditation et spiritualité', 'Événements et Inscriptions'].each do |category| %>
        <div class="checkbox-group">
          <%= check_box_tag "subscriber[category]", category, @subscriber.category == category, id: "category_#{category.parameterize}" %>
          <%= label_tag "category_#{category.parameterize}", category %>
        </div>
      <% end %>
      <div class="cstm-btn-container">
        <%= f.submit "S'inscrire à la Newsletter", class: "cstm-btn" %>
      </div>
    <% end %>
  </div>
<% end %>